### PR TITLE
Add config variable for https or http urls

### PR DESCRIPTION
**Pull request by blomdahldaniel**
Allows the developer to change the config variable for https or http urls.
Ofc one should always use SSL cert but in my setup right now I dont run SSL in development.

Don't know if there is more generated urls in there though...?

### CODE REVIEW

**Comment by iantasker** [comment]
@blomdahldaniel  Great suggestion, I have checked and secure_url was only used in the places you found.

**Comment by iantasker** [comment]
@blomdahldaniel To support backwards compatibility with preexisting installation that my not have the config variable set please can you make the following change to the pull request? 

From ```if (config('sparkinvite.https')) { ``` to ``` if (config('sparkinvite.https', true)) { ```

This will ensure that urls stay https after this update and not change to http

**Comment by blomdahldaniel** [comment]
@iantasker aah, ofc! Good catch!

**Comment by iantasker** [comment]
@blomdahldaniel Thanks, this is good to go so will merge in. If you get the chance please can you submit a pull request with an updated read me documenting the config setting? 

I will also chat with @drjonnicholson about releasing a 1.0.0 version.

**Comment by blomdahldaniel** [comment]
@iantasker imho there is a lot that has to be done regarding the documentation before a v1.0 is ready..? Imho almost an entire rewrite of the readme would be in place.

**Comment by iantasker** [comment]
@blondalhdaniel I was thinking more feature wise than documentation, but take your point on board. 

If you can outline (add to issue #6) what you want to see from the documentation for v1.0.0 we can then update it.

**Comment by iantasker** [comment]
I've locked this conversation so it can continue in issue #6

**Pull request merged**
